external_components:
  - source: github://Ra3mbl/esphome_chiq_ac_component
    components: [ chiq_ac ]
    refresh: 0s

esphome:
  name: chiq-air-conditioner

esp8266:
  board: esp12e

wifi:
  ssid: "WIFI SSID"
  password: "WIFI PASSWORD"

logger:
  level: DEBUG
  baud_rate: 0

api:

ota:
  - platform: esphome

uart:
  id: ac_uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

climate:
  - platform: chiq_ac
    name: "CHiQ AC"
    current_temperature:
      name: "CHiQ Current Temperature"
    turbo_state:
      name: "CHiQ Turbo"
    ionizer_state:
      name: "CHiQ Ionizer"
    quiet_state:
      name: "CHiQ Quiet"
