external_components:
  - source: github://Ra3mbl/esphome_dexp_ac_component
    components: [ dexp_ac ]
    refresh: 0s

esphome:
  name: dexp-air-conditioner

esp8266:
  board: esp12e

wifi:
  ssid: "WIFI SSID"
  password: "WIFI PASSWORD"

logger:
  level: DEBUG
  baud_rate: 0

api:

ota:
  - platform: esphome

uart:
  id: ac_uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

climate:
  - platform: dexp_ac
    name: "DEXP AC"
    current_temperature:
      name: "DEXP Current Temperature"
    turbo_state:
      name: "DEXP Turbo"
    ionizer_state:
      name: "DEXP Ionizer"
    quiet_state:
      name: "DEXP Quiet"
